services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
    ports:
      - 9200:9200
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
    networks:
      - elk
    command: ["-f", "/usr/share/logstash/pipeline/pipeline.conf"]

  kibana:
  image: docker.elastic.co/kibana/kibana:7.10.2
  container_name: kibana
  environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - ELASTICSEARCH_USERNAME=elastic    # Kibana login username
    - ELASTICSEARCH_PASSWORD=changeme   # Kibana login password
  ports:
    - 5601:5601
  depends_on:
    - elasticsearch
  networks:
    - elk


networks:
  elk:
    driver: bridge
